### ISSUE TITLE
Example of Prometheus Alert

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#609]
alert of
- exceeding delay
- job failure

**Comment by LordofAvernus** [comment]
example for delay alert 
https://actiontech.github.io/dtle-docs-cn/3/3.4.1_delay_alert.html

**Comment by asiroliu** [comment]
# 验证
# version:
```
9.9.9.9-master-eb010e4
```
1. deolpy dtle cluster
2. create job
```
job "test" {
  datacenters = ["dc1"]

  group "Src" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-src-1"
      }
    task "src" {
      driver = "dtle"
      config {
        ReplicateDoDb = [{
          TableSchema = "test"
        }]
        ConnectionConfig = {
          Host = "10.186.16.109"
          Port = 3306
          User = "test"
          Password = "test"
        }
      }
    }
  }
  group "Dest" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-dest-1"
      }
    task "dest" {
      driver = "dtle"
      config {
        ConnectionConfig = {
          Host = "10.186.16.117"
          Port = 3306
          User = "test"
          Password = "test"
        }
      }
    }

  }
}
```
3. prometheus.yml
```
shell> cat prometheus.yml
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["127.0.0.1:9094"]

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'nomad'
    scrape_interval: 15s
    metrics_path: '/v1/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['10.186.63.20:4646']
        labels:
          instance: nomad-src-1
      - targets: ['10.186.63.76:4646']
        labels:
          instance: nomad-dest-1

  - job_name: 'dtle'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.186.63.20:8190']
        labels:
          instance: dtle-src-1
      - targets: ['10.186.63.76:8190']
        labels:
          instance: dtle-dest-1
```
4. alert.rules
```
shell> cat alert.rules
groups:
- name: simple_example
  rules:

  # Alert for task that is delay more than 5s for >1 minutes.
  - alert: TaskDelay
    expr:  dtle_delay_time > 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "task {{ $labels.task_name }} has delay"
      description: "Task {{ $labels.task_name }} of instance {{ $labels.instance }} has delay 5s  more than 1 minutes."
```
5. alertmanager.yml
```
shell> cat alertmanager.yml
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'SENDER_ACCOUNT'
  smtp_auth_username: 'SENDER_ACCOUNT'
  smtp_auth_password: 'email smtp verify password'
  smtp_require_tls: false
route:
  # If an alert has successfully been sent, wait 'repeat_interval' to resend them.
  repeat_interval: 10s
  #  A default receiver
  receiver: team-dtle-mails

receivers:
  - name: 'team-dtle-mails'
    email_configs:
    - to: 'receiver@actionsky.com'
```
6. create prometheus server
```
shell> docker run -itd -p 9099:9090 --name=prometheus_1 --hostname=prometheus_1 --restart=always -v ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml -v ${PWD}/alert.rules:/etc/prometheus/alert.rules prom/prometheus
```
7. create alertmanager server
```
shell> docker run -itd -p 9094:9093 -v /data/liuan/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml prom/alertmanager
```
